# Generated by Django 5.1.2 on 2025-04-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_blogpost_cover_image_blogpost_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='summary',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
